kubernetes:
  namespace: train-ticket
  kubeconfig: ~/.kube/config
  manifest: ''
prometheus:
  range_url: http://localhost:9091/api/v1/query_range
  query_url: http://localhost:9091/api/v1/query
  step: 5
autoscaler:
  slo: 500
  max_pod: 5
  min_pod: 1
  duration: 660
  simulation_model: simulation/train_ticket/RandomForestClassify.model
output:
  data_dir: output
